import { Adapter } from './adapter';
import type { CollectionSlug, Payload, TypedCollection } from 'payload';

export interface PayloadArgs {
  draft?: boolean;
  locale?: string;
}

export class PayloadAdapter<Slug extends CollectionSlug> extends Adapter<TypedCollection[Slug], [PayloadArgs?]> {
  constructor(
    private payload: Payload,
    private slug: Slug,
  ) {
    super();
  }

  // @ts-expect-error no guarantees on the type of the instance generated by create is provided so TS cannot know that it is the same as the instance passed in
  async save(
    instance: Omit<TypedCollection[Slug], 'id'> | Omit<TypedCollection[Slug], 'id'>[],
    { draft = false, locale = 'en' }: PayloadArgs = { draft: false, locale: 'en' },
  ): Promise<TypedCollection[Slug] | TypedCollection[Slug][]> {
    const instances = Array.isArray(instance) ? instance : [instance];
    const savedInstances = await Promise.all(
      instances.map((data) =>
        this.payload.create({
          collection: this.slug,
          data,
          draft,
          locale,
        }),
      ),
    );
    return Array.isArray(instance) ? savedInstances : savedInstances[0];
  }
}
