import { Factory } from '../factory';
import type { CollectionSlug, Payload, TypedCollection } from 'payload';
import { PayloadAdapter, PayloadArgs } from '../adapters/payload.adapter';

export abstract class PayloadFactory<Slug extends CollectionSlug> extends Factory<
  TypedCollection[Slug],
  [PayloadArgs?]
> {
  constructor(
    protected payload: Payload,
    protected slug: Slug,
  ) {
    super();
    // @ts-expect-error no guarantees on the type of the instance generated by create is provided so TS cannot know that it is the same as the instance passed in
    this.adapter = new PayloadAdapter<Slug>(payload, slug);
  }
}
